version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: captainhook/plugin-composer
    versions:
    - 5.2.4
  - dependency-name: bitexpert/captainhook-infection
    versions:
    - 0.4.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.73
    - 0.12.76
