language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
  - php: 7.0
  - php: 7.1

before_install:
  - if [[ $encrypted_dcf04ab9e4c0_key != '' ]]; then openssl aes-256-cbc -K $encrypted_137bf9c56685_key -iv $encrypted_137bf9c56685_iv -in auth.json.enc -out auth.json -d ; fi

before_script:
  - composer self-update
  - composer validate

script:
  - if [[ $encrypted_dcf04ab9e4c0_key != '' ]]; then composer install --prefer-source ; fi
  - if [[ $encrypted_dcf04ab9e4c0_key != '' ]]; then composer test ; fi
