name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        coveralls: [false]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'
            coveralls: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install

      - name: Linting code
        run: ./vendor/bin/phing lint

      - name: Codesniffer
        run: ./vendor/bin/phing sniff

      - name: Static code analysis
        run: ./vendor/bin/phing analyse

      - name: Magerun
        if: matrix.coveralls == false
        run: |
          wget https://files.magerun.net/n98-magerun2-latest.phar
          mkdir -p ~/.n98-magerun2/modules
          ln -s $(pwd) ~/.n98-magerun2/modules/magerun2-password-normalizer
          php n98-magerun2-latest.phar help dev:customer:normalize-passwords

      - name: Unittests
        if: matrix.coveralls == false
        run: ./vendor/bin/phing unit

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: ./vendor/bin/phing unit-with-coverage

      - name: Infection for added files
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          ./vendor/bin/infection -j2 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
